### PR TITLE
Java installation process enhancements

### PR DESCRIPTION
**Pull request by JakubVanek**
Future possible improvements:
* using the future java shell wrapper config files
* using /usr/lib/jvm/.*.jinfo files for java alternative switching

### CODE REVIEW

**Comment by jabrena** [comment]
Hi @JakubVanek 

Is it possible if we merge this positive change in the next release?
I tested current code and If I merge, I will requiere few hours more.

Is it ok for you?

Juan Antonio

**Comment by JakubVanek** [comment]
It might be OK for me, but the previous update code is **broken**.

```sh
if type -p java; then
    echo "Found java executable in PATH"
    JAVA_REAL_EXE="$(which java)"

    if [ ! -d "$JRI_OPT/jri-10-build-050" ]; then
        echo "But we will upgrade the Java version"
        echo $JRI_OPT/jri-10-build-050
        echo
        if [ "$PLATFORM" == "ev3" ]; then
            java_install_bundle
        elif [ "$PLATFORM" == "brickpi"  ] ||
             [ "$PLATFORM" == "brickpi3" ] ||
             [ "$PLATFORM" == "pistorms" ]; then
            java_install_ppa
        fi
    else
      echo "Latest Java installed."
      echo $JRI_OPT/jri-10-build-050
    fi

elif ...
```
We don't have `jri-10-build-050` on non-EV3 platforms.

**Comment by JakubVanek** [comment]
This is another instance of broken code -- we're saying we're going to update, but nothing will happen.
```sh
elif [[ -n "$JAVA_HOME" ]] && [[ -x "$JAVA_HOME/bin/java" ]];  then
    echo "Found java executable in JAVA_HOME"
    JAVA_REAL_EXE="$JAVA_HOME/bin/java"

    echo $JRI_OPT/jri-10-build-050
    if [ ! -d "$JRI_OPT/jri-10-build-050" ]; then
        echo "But upgrading Java version"
        echo
    fi

else
```

**Comment by JakubVanek** [comment]
I should've described what this patch does in more detail than "some enhancement", I'm sorry for that.

**Comment by jabrena** [comment]
Oki, tomorrow, I will merge. :)

**Comment by jabrena** [comment]
Merging

**Comment by jabrena** [comment]
Merging

**Pull request merged**
